# Generated by Django 4.2.5 on 2023-09-16 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('short_url', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('expiry_time', models.DateTimeField(default=datetime.datetime(2023, 9, 23, 14, 10, 35, 946668, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
